//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMI_SOAP_CLIENT.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bmi", Namespace="http://schemas.datacontract.org/2004/07/BMI_WCF_SOAP")]
    [System.SerializableAttribute()]
    public partial class Bmi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BmiValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RiskField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BmiValue {
            get {
                return this.BmiValueField;
            }
            set {
                if ((this.BmiValueField.Equals(value) != true)) {
                    this.BmiValueField = value;
                    this.RaisePropertyChanged("BmiValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GetLink {
            get {
                return this.GetLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.GetLinkField, value) != true)) {
                    this.GetLinkField = value;
                    this.RaisePropertyChanged("GetLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string More {
            get {
                return this.MoreField;
            }
            set {
                if ((object.ReferenceEquals(this.MoreField, value) != true)) {
                    this.MoreField = value;
                    this.RaisePropertyChanged("More");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Risk {
            get {
                return this.RiskField;
            }
            set {
                if ((object.ReferenceEquals(this.RiskField, value) != true)) {
                    this.RiskField = value;
                    this.RaisePropertyChanged("Risk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/myBMI", ReplyAction="http://tempuri.org/IService1/myBMIResponse")]
        double myBMI(int height, int weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/myBMI", ReplyAction="http://tempuri.org/IService1/myBMIResponse")]
        System.Threading.Tasks.Task<double> myBMIAsync(int height, int weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/myHealth", ReplyAction="http://tempuri.org/IService1/myHealthResponse")]
        BMI_SOAP_CLIENT.ServiceReference1.Bmi myHealth(int height, int weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/myHealth", ReplyAction="http://tempuri.org/IService1/myHealthResponse")]
        System.Threading.Tasks.Task<BMI_SOAP_CLIENT.ServiceReference1.Bmi> myHealthAsync(int height, int weight);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : BMI_SOAP_CLIENT.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<BMI_SOAP_CLIENT.ServiceReference1.IService1>, BMI_SOAP_CLIENT.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double myBMI(int height, int weight) {
            return base.Channel.myBMI(height, weight);
        }
        
        public System.Threading.Tasks.Task<double> myBMIAsync(int height, int weight) {
            return base.Channel.myBMIAsync(height, weight);
        }
        
        public BMI_SOAP_CLIENT.ServiceReference1.Bmi myHealth(int height, int weight) {
            return base.Channel.myHealth(height, weight);
        }
        
        public System.Threading.Tasks.Task<BMI_SOAP_CLIENT.ServiceReference1.Bmi> myHealthAsync(int height, int weight) {
            return base.Channel.myHealthAsync(height, weight);
        }
    }
}
